spring:
  datasource:
    hikari:
      maximum-pool-size: 1
  jpa:
    generate-ddl: true

jpa:
  properties:
    hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      ddl-auto: create
      show-sql: true

auth:
  jwt:
    issuer: team.sparta.com
    secret: fjosj8efhsua3h3fah3ilhfioah3
    accessTokenExpirationHour: 168

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
